import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import Col from "react-bootstrap/Col";
import Row from "react-bootstrap/Row";
import CourseCarousel from "@/components/CourseCarousel";
import ReactPlayer from "react-player";
import Card from "react-bootstrap/Card";
import Image from "next/image";
import courseimage1 from "../assets/courses/fallprotection5.jpg";
import courseimage2 from "../assets/courses/hazcom4.jpg";
import Accordion from "react-bootstrap/Accordion";
import Form from "react-bootstrap/Form";
import whiteLogo from "../assets/jjsafety__logo--white.png";
import Header from "@/layout/Header";

export default function Home() {
  const [videoEnded, setVideoEnded] = useState(false);
  const homeVideo = "https://player.vimeo.com/video/499311020";
  const [hasWindow, setHasWindow] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setHasWindow(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.topsection}>
          <div className={styles.topcontent}>
            <h1>
              Complete Your OSHA
              <br /> Training Online
            </h1>
            <Button>Try It Free</Button>
          </div>
        </section>

        <Container>
          <CourseCarousel />
        </Container>

        {hasWindow && (
          <ReactPlayer
            className={styles.video}
            onReady={() => {
              setVideoEnded(false);
            }}
            onEnded={() => {
              setVideoEnded(true);
            }}
            url={homeVideo}
            controls
          ></ReactPlayer>
        )}

        <br />
        <br />
        <Container className={styles.containers}>
          <Row>
            <Col md={12}>
              <h2 style={{ textAlign: "center" }}>
                <b>
                  Get Compliant <br /> On your terms.
                </b>
              </h2>
            </Col>
          </Row>
          <Row>
            <Col md={6}>
              <Card className={styles.oshacards}>
                <h2 className={styles.headertwo}>
                  Introducing Fall Protection, our latest training module
                  created to keep your workers safe from fall hazards.
                </h2>
                <Image
                  className={styles.courseImages}
                  src={courseimage1}
                  alt="course image"
                />
              </Card>
            </Col>
            <Col md={6}>
              <Card className={styles.oshacards}>
                <h2 className={styles.headertwo}>
                  OSHA compliance has never been simpler with our Introduction
                  to OSHA training. Get certified today!
                </h2>
                <Image
                  className={styles.courseImages}
                  src={courseimage2}
                  alt="course image"
                />
              </Card>
            </Col>
          </Row>
          <Row>
            <Col md={6}>
              <Card className={styles.oshacards}>
                <h2 className={styles.headertwo}>
                  Introducing Fall Protection, our latest training module
                  created to keep your workers safe from fall hazards.
                </h2>
                <Image
                  className={styles.courseImages}
                  src={courseimage1}
                  alt="course image"
                />
              </Card>
            </Col>
            <Col md={6}>
              <Card className={styles.oshacards}>
                <h2 className={styles.headertwo}>
                  OSHA compliance has never been simpler with our Introduction
                  to OSHA training. Get certified today!
                </h2>
                <Image
                  className={styles.courseImages}
                  src={courseimage2}
                  alt="course image"
                />
              </Card>
            </Col>
          </Row>
          <br />
          <Row>
            <Col md={12}>
              <h1 style={{ textAlign: "center" }}>
                It's as easy as it sounds.
              </h1>
            </Col>
          </Row>
          <Row>
            <Col md={12}>
              <Accordion>
                <Accordion.Item eventKey="0">
                  <Accordion.Header>What is JJ LMS</Accordion.Header>
                  <Accordion.Body>
                    JJ LMS is an online learning management system for training
                    employees to follow OSHA safety standards and to avoid
                    penalties and fines during site visits. Access your online
                    training anytime, anyplace and get instant grading and
                    online certificates. The JJ LMS interactive multimedia
                    courses will keep your employees engaged and informed. The
                    JJ LMS course catalog includes both construction and general
                    industry.
                  </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="1">
                  <Accordion.Header>
                    What are the benefits of JJ LMS
                  </Accordion.Header>
                  <Accordion.Body>
                    JJ LMS provides an affordable, customizable learning
                    management system that your employees can access around the
                    clock from any desktop PC, tablet, or smartphone. Get
                    in-depth course completion reporting, instant grading, and
                    online certificates. Our dedicated support team is here to
                    help with any issues.
                  </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="2">
                  <Accordion.Header>How do I try JJ LMS</Accordion.Header>
                  <Accordion.Body>
                    Simply click the "Try it free" button in the upper-right
                    corner. Call the phone number provided and we will set up
                    your 7-day free trial.
                  </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="3">
                  <Accordion.Header>What does it cost?</Accordion.Header>
                  <Accordion.Body>
                    That all depends on how many employees need training. We
                    have the pricing broken down into annual cost effective
                    solutions for all company sizes: 1–10 employees is $100 per
                    user per year, 11–20 employees is $95 per user per year,
                    21–30 employees is $90 per user per year, 31–40 employees is
                    $85 per user per year, 41–50 employees is $80 per user per
                    year, and for 50 or more employees give us a call for a
                    customized price!
                  </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="4">
                  <Accordion.Header>
                    Do my employees need to register too?
                  </Accordion.Header>
                  <Accordion.Body>
                    No, we make it super easy for you. No need for tedious
                    inputting of employee information. We will provide you with
                    an employee roster template. Simply complete the template
                    and email it in to us, and we will upload all of your
                    employees and notify you to start assigning courses.
                  </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="5">
                  <Accordion.Header>How do I access JJ LMS</Accordion.Header>
                  <Accordion.Body>
                    All you need is a web browser and an internet connection.
                    The JJ LMS website is responsive and can be accessed via
                    desktop computer, tablet, or smartphone. Certificates for
                    each course can be downloaded on any device as a PDF.
                  </Accordion.Body>
                </Accordion.Item>
              </Accordion>
            </Col>
          </Row>
          <Row>
            <Col md={12}>
              <br />
              <br />
              <Card className={styles.regularcard}>
                <Image
                  className={styles.whitelogo}
                  src={whiteLogo}
                  alt="jj white logo"
                />
                <p>
                  Try the first chapter of Walking-Working Surfaces for Free by
                  joining our newsletter!
                </p>
                <Form>
                  <Form.Group controlId="formBasicEmail">
                    <Form.Control type="email" placeholder="Enter email" />
                    <br />
                  </Form.Group>
                  <Button className={styles.newsletterbtn} type="submit">
                    Submit
                  </Button>
                </Form>
              </Card>
            </Col>
          </Row>
        </Container>
        <br />
        <br />
      </main>
    </>
  );
}
